export const ERRORCODES = {
  INVALID_STOCK_TICKER: 'INVALID_STOCK_TICKER',
  NOT_FOUND_BUYING_TRANSACTION: 'NOT_FOUND_BUYING_TRANSACTION',
  LESS_THAN_BUYING_QUANTITY: 'LESS_THAN_BUYING_QUANTITY',
};
